### ISSUE TITLE
Config file /etc/mysql/my.cnf needs to belong to user mysql

### ISSUE THREAD

**Issue by jharbott** [dev-sec/chef-percona-hardening#1]
Otherwise, when using clustering and a new node is added into the cluster, the node selected as donor shows this error in `/var/lib/mysql/innobackup.backup.log`:

```
Could not open required defaults file: /etc/mysql/my.cnf
Fatal error in defaults handling. Program aborted
xtrabackup: Error: --defaults-file must be specified first on the command line
innobackupex: Error: no 'mysqld' group in MySQL options at /usr//bin/innobackupex line 4407.
```

Doing a `chown mysql /etc/mysql/my.cnf` fixes this error.

**Comment by chris-rock** [comment]
@jrosenboom please go ahead. I am happy to merge a pull request. I think we should use default["percona"]["server"]["username"]  to reuse the configuration from percona cookbook.
